apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T13:33:15Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5086"
  uid: ca6a8c3a-3c49-41f3-a2c4-b8091d50f1bb
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.253.54
  clusterIPs:
  - 10.103.253.54
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30469
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
